#! /usr/bin/python
#
# Copyright 2015 Adam Greenstein <adamgreenstein@comcast.net>
# 
# node_server is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# node_server is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with node_server.  If not, see <http://www.gnu.org/licenses/>.

from multiprocessing.managers import BaseManager
from threading import Lock
from utils.generator import GraphBuilder
from utils.manager import CacheManager

main_lock = Lock()
graph = None
meta = None
max_dist = None

def create_meta_data(graph):
    temp = {}
    maximum = 0
    data = graph[0]
    for i in data:
        distance = int(i['label'])
        temp[i['id']] = distance
        if distance > maximum:
            maximum = distance
    return temp, maximum

def get_cache():
    global graph
    global main_lock
    with main_lock:
        return graph

def get_meta_data():
    global meta
    global max_dist
    global main_lock
    with main_lock:
        return meta, max_dist

def reload_cache():
    global graph
    global meta
    global max_dist
    global main_lock
    print "Reloading Cache..."
    temp = gb.get_data()
    print "Creating Meta Data..."
    temp_meta, temp_max = create_meta_data(temp)
    with main_lock:
        del graph
        del meta
        del max_dist
        graph = temp
        meta = temp_meta
        max_dist = temp_max
    print "Reloaded\n"


gb = GraphBuilder('./config.ini')

print "Launching Server..."
reload_cache()
cache_loader = CacheManager(reload_cache, gb.com_port)
cache_loader.run()
manager = BaseManager(address=('', gb.port), authkey=gb.auth)
manager.register('get_cache', callable=get_cache, exposed=('__getitem__',))
manager.register('get_meta_data', callable=get_meta_data, exposed=('__getitem__',))
manager.get_server().serve_forever()
